name: build_and_upload

on: [ push, pull_request ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.8

        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Create PR from release against master
        uses: medlypharmacy/create-pr-action@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: release
          BASE_BRANCH: master
